### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by bassimeledath** [bassimeledath/Podsicle#1]
### 1. Read Paper and set up weekly meetings
@bassimeledath  @zoelesv @liavila 
- [x] **Familiarize yourself with the foundational paper for Popsicle's logic** [Paper Link](https://arxiv.org/abs/2402.14207)
    - [ ] @igarciamontoya 
- [x] **Setup weekly meeting schedule** 

### 2. Creative Assets
@igarciamontoya @zoelesv 
- [ ] **Logo**: Design or finalize the logo for Popsicle.
- [ ] **Slogan**: Come up with a catchy slogan.
- [ ] **Color Palette**: Decide on the color palette.
Brainstorming moodboard: [Link](https://docs.google.com/presentation/d/1SHYexohxPbvkgkFgMFugMexfOuK1BntugcQqJtmhLns/edit?usp=sharing)
### 3. Data Sources
@liavila 
- [ ] **Transcripts for Testing**: Collect transcripts from podcasts for emulation and evaluation purposes.

### 4. Text to Speech API
@igarciamontoya @zoelesv 
- [x] **API Research**: Find text to speech API options that are human-sounding, fast, and cost-effective. Try to make it work on a jupyter notebook.

### 5. Systems Design and Feature Spec 
@bassimeledath 
- [ ] **High-Level Design**: Outline the high-level systems design and feature specifications of the app.

### 6. Python Code for LLM Conversation
- [ ] **Template Code**: Write Python code in a Jupyter notebook facilitating a short conversation between two LLMs.
- [ ] **BONUS - Conversation History**: Incorporate access to conversation history for both LLMs.
